version: 2
jobs:
  build:
    machine:
      environment:
        STACK_YAML: stack-ghc-7.8.4.yaml
#  - STACK_YAML=stack-ghc-7.10.3.yaml
#  - STACK_YAML=stack.yaml
#  - STACK_YAML=stack-ghc-8.2.1.yaml
#  - STACK_YAML=stack-ghcjs-0.2.1.9007019.yaml        
        
    steps:
      - checkout
  
#cache:
#  directories:
#    - $HOME/.tinc/cache
#    - $HOME/.stack

#language: c

#addons:
#  apt:
#    packages:
#      - libgmp-dev
