version: 2
jobs:
  build:
    machine:
      environment:
        STACK_YAML: stack-ghc-7.8.4.yaml
#  - STACK_YAML=stack-ghc-7.10.3.yaml
#  - STACK_YAML=stack.yaml
#  - STACK_YAML=stack-ghc-8.2.1.yaml
#  - STACK_YAML=stack-ghcjs-0.2.1.9007019.yaml        
        
    steps:
      - checkout
      - run: |
          mkdir -p ~/.local/bin
          export PATH=$HOME/.local/bin:$PATH
          curl -L https://www.stackage.org/stack/linux-x86_64 | tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack'
          stack --version
          stack setup --no-terminal
          cd $HOME/.local/bin && wget https://zalora-public.s3.amazonaws.com/tinc && chmod +x tinc
  
#cache:
#  directories:
#    - $HOME/.tinc/cache
#    - $HOME/.stack

#language: c

#addons:
#  apt:
#    packages:
#      - libgmp-dev
