version: 2
jobs:
  build:
    machine: true

    steps:
      - checkout
      - run: yamls=(
          stack-ghc-7.8.4.yaml
          stack-ghc-7.10.3.yaml
          stack.yaml
          stack-ghc-8.2.1.yaml
          stack-ghcjs-0.2.1.9007019.yaml
         ) && echo $yamls && echo ${yamls[$CIRCLE_NODE_INDEX]} && echo 'export STACK_YAML=${yamls[$CIRCLE_NODE_INDEX]}' >> $BASH_ENV
      - run: echo $STACK_YAML
      - run: cat $BASH_ENV

      - run: echo 'export PATH=$HOME/.local/bin:$PATH' >> $BASH_ENV
      - run: sudo apt-get install libgmp-dev
      - run: mkdir -p ~/.local/bin
      - run: curl -L https://www.stackage.org/stack/linux-x86_64 | tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack'
      - run: stack --version
      - run: stack setup --no-terminal
      - run: cd $HOME/.local/bin && wget https://zalora-public.s3.amazonaws.com/tinc && chmod +x tinc
      - run: if [ "$STACK_YAML" = "stack-ghc-8.2.1.yaml" ]; then HOMEMODULES="--ghc-options=-Wno-missing-home-modules"; fi
      - run: if [ "$TRAVIS_EVENT_TYPE" = "cron" ] ; then ./scripts/ci-cron.sh ; else stack test $HOMEMODULES --ghc-options=-Werror --no-terminal ; fi
  
#cache:
#  directories:
#    - $HOME/.tinc/cache
#    - $HOME/.stack

#language: c

#addons:
#  apt:
#    packages:
#      - libgmp-dev
